Fixing wrong error checking in List and ListAll functions
johanneswuerbach/nfsexports pull request #6
Opened 2019-05-29 17:36 UTC by huguesalary

2019-05-29 18:45 UTC, johanneswuerbach requested changes

2019-05-29 18:45 UTC, johanneswuerbach commented on nfsexports.go
> +	if err = scanner.Err(); err != nil {
You should use := in this case to not use the outer scope err but actually declare a new variable

2019-05-29 19:34 UTC, huguesalary commented
You're right. Just fixed it

2019-05-30 07:54 UTC, johanneswuerbach commented
Thanks again 👍

2019-05-30 07:54 UTC, merged